// Package deviceLogs provides APIs to retrieve device-generated
// logs for nodes within the Anedya platform.
package deviceLogs

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/anedyaio/anedya-go-sdk/common"
	"github.com/anedyaio/anedya-go-sdk/errors"
)

// GetLogsRequest represents the payload used to fetch logs
// generated by a device (node) within a given time range.
type GetLogsRequest struct {
	// NodeID is the unique identifier of the node whose logs are requested.
	NodeID string `json:"nodeid"`

	// From is the starting timestamp (Unix milliseconds) for log retrieval.
	From int64 `json:"from"`

	// To is the optional ending timestamp (Unix milliseconds).
	// If omitted, logs are fetched from the "From" timestamp onwards.
	To int64 `json:"to,omitempty"`

	// Order specifies the sorting order of logs.
	// Allowed values are "asc" or "desc".
	Order string `json:"order,omitempty"`

	// Limit specifies the maximum number of log entries to return.
	// Valid range is 0–1000.
	Limit int `json:"limit,omitempty"`
}

// LogEntry represents a single log entry generated by a device.
type LogEntry struct {
	// Timestamp indicates when the log was generated (Unix milliseconds).
	Timestamp int64 `json:"timestamp"`

	// Log contains the actual log message.
	Log string `json:"log"`
}

// getLogsAPIResponse represents the raw API response
// returned by the Get Logs API.
type getLogsAPIResponse struct {
	common.BaseResponse

	// Count represents the total number of logs returned.
	Count int `json:"count"`

	// Data contains the list of log entries.
	Data []LogEntry `json:"data"`
}

// GetLogsResult represents the processed and user-facing
// result returned by the GetLogs method.
type GetLogsResult struct {
	// Count represents the number of logs returned.
	Count int

	// Data contains the list of retrieved log entries.
	Data []LogEntry
}

// GetLogs retrieves logs generated by a specific node within
// a given time range.
//
// Steps performed by this method:
//  1. Validate request parameters.
//  2. Marshal the request payload into JSON.
//  3. Build and send a POST request to the Logs API.
//  4. Decode the API response.
//  5. Convert the API response into a user-friendly result.
//
// Parameters:
//   - ctx: Context used to control request lifecycle, cancellation, and deadlines.
//   - req: Pointer to GetLogsRequest containing log query parameters.
//
// Returns:
//   - (*GetLogsResult, nil) if logs are fetched successfully.
//   - (nil, error) for validation or client-side failures.
//   - (nil, error) when the API responds with an error.
func (dm *DeviceLogManagement) GetLogs(
	ctx context.Context,
	req *GetLogsRequest,
) (*GetLogsResult, error) {

	// validate request
	if req == nil {
		return nil, &errors.AnedyaError{
			Message: "get logs request cannot be nil",
			Err:     errors.ErrRequestNil,
		}
	}

	// node ID is mandatory
	if req.NodeID == "" {
		return nil, &errors.AnedyaError{
			Message: "nodeid is required",
			Err:     errors.ErrInvalidNodeID,
		}
	}

	// from timestamp must be valid
	if req.From <= 0 {
		return nil, &errors.AnedyaError{
			Message: "from timestamp must be valid",
			Err:     errors.ErrInvalidTimeRange,
		}
	}

	// validate from/to timestamp range
	if req.To != 0 && req.To < req.From {
		return nil, &errors.AnedyaError{
			Message: "invalid from/to timestamp range",
			Err:     errors.ErrInvalidTimeRange,
		}
	}

	// validate limit bounds
	if req.Limit < 0 || req.Limit > 1000 {
		return nil, &errors.AnedyaError{
			Message: "limit must be between 0 and 1000",
			Err:     errors.ErrInvalidInput,
		}
	}

	// validate order value
	if req.Order != "" && req.Order != "asc" && req.Order != "desc" {
		return nil, &errors.AnedyaError{
			Message: "order must be asc or desc",
			Err:     errors.ErrInvalidOrder,
		}
	}

	// build API URL
	url := fmt.Sprintf("%s/v1/logs/getLogs", dm.baseURL)

	// marshal request body
	body, err := json.Marshal(req)
	if err != nil {
		return nil, &errors.AnedyaError{
			Message: "failed to encode GetLogs request",
			Err:     errors.ErrRequestEncodeFailed,
		}
	}

	// create HTTP request with context
	httpReq, err := http.NewRequestWithContext(
		ctx,
		http.MethodPost,
		url,
		bytes.NewBuffer(body),
	)
	if err != nil {
		return nil, &errors.AnedyaError{
			Message: "failed to build GetLogs request",
			Err:     errors.ErrRequestBuildFailed,
		}
	}

	// execute HTTP request
	resp, err := dm.httpClient.Do(httpReq)
	if err != nil {
		return nil, &errors.AnedyaError{
			Message: "failed to execute GetLogs request",
			Err:     errors.ErrRequestFailed,
		}
	}
	defer resp.Body.Close()

	// decode API response
	var apiResp getLogsAPIResponse
	if err := json.NewDecoder(resp.Body).Decode(&apiResp); err != nil {
		return nil, &errors.AnedyaError{
			Message: "failed to decode GetLogs response",
			Err:     errors.ErrResponseDecodeFailed,
		}
	}

	// handle API-level errors
	if !apiResp.Success {
		return nil, errors.GetError(apiResp.ReasonCode, apiResp.Error)
	}

	// return processed result
	return &GetLogsResult{
		Count: apiResp.Count,
		Data:  apiResp.Data,
	}, nil
}
