package deviceLogs

import "net/http"

// DeviceLogManagement provides methods to interact with
// device log–related APIs exposed by the platform.
//
// It manages the HTTP client and base URL required to
// fetch logs generated by nodes.
type DeviceLogManagement struct {
	httpClient *http.Client
	baseURL    string
}

// NewDeviceLogManagement creates and returns a new instance
// of DeviceLogManagement.
//
// Parameters:
//   - httpClient: Optional custom HTTP client used to make API requests.
//     If nil, http.DefaultClient is used.
//   - baseURL: Base URL of the API server.
//
// This constructor ensures a valid HTTP client is always
// available for executing device log API requests.
func NewDeviceLogManagement(
	httpClient *http.Client,
	baseURL string,
) *DeviceLogManagement {

	if httpClient == nil {
		httpClient = http.DefaultClient
	}

	return &DeviceLogManagement{
		httpClient: httpClient,
		baseURL:    baseURL,
	}
}
